language: python

python:

  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"   
  - "3.7"
  - "3.8"
  - "3.9"
install:
  - pip install coverage
  - pip install -r requirements.txt

script:
  - coverage run test.py

after_success:
  - coverage xml
  - bash <(curl -s https://codecov.io/bash)
