language: python

python:

  - "2.7"
install:
  - pip install coverage

script:

  - python -m unittest
  - coverage run test.py

after_success:
  - coverage xml
  - bash <(curl -s https://codecov.io/bash)
